### ISSUE TITLE
[Maintenance] Clarify integration maintenance

### ISSUE THREAD

**Issue by simonhir** [it-at-m/refarch#128]
### Problem description

Currently it's not really clear who is responsible for integrations.

### Desired solution

Clarify who is responsible for the lifecycling of integrations.
Possibilities are:
- Refarch maintainers
- Person who provided PR

Probably can be different for different integrations.

**Comment by simonhir** [comment]
@boal asked for the possibility of adding a integration for arcgis.
Since I didn't even know what that is, I'm wondering who will be responsible for the lifecycling of integrations in the future.

First of all in my opinion, there is no reason not to add further integrations if they are used by several projects.
But to prevent them from not being maintained there should be clarified who is responsible for them once added.

My suggestion would be core-once (i.e. mail, s3, ...) are maintained by the refarch-maintainers and for the other once a contact person is defined.

@DanielOber @devtobi what do you think?

**Comment by darenegade** [comment]
I think that integrations should only be included if they fit into the overall concept of RefArch and are likely to be reused by several projects. In my opinion, adopting integrations that are not maintained by a permanent team makes the adoption pointless and could be maintained in separate repos so that we don't run the risk that no one feels responsible for it and it becomes obsolete.
It goes without saying that you can of course still contact the original author if you have any questions.

**Comment by devtobi** [comment]
Maintenance of integrations will be done by us. We just need to make sure we don't accept every small integration as this increases lifecycle effort on our side.
