### ISSUE TITLE
[Bug] Security vulnerability in Spring security using Spring Boot 3.3.3

### ISSUE THREAD

**Issue by hupling** [it-at-m/refarch#161]
### Bug description

https://artifacthub.io/packages/helm/it-at-m/refarch-gateway?modal=security-report

The Security Report from artifacthub says that you need to update spring boot security.

Why don't you add the version number to your pom. https://github.com/it-at-m/refarch/blob/22ffdb7712acb9ec6a80e70905e90b5b5ec2ee36/refarch-gateway/pom.xml#L133

### Expected behaviour

-

### Steps for reproduction

-

### Affected version

-

### No duplicate

- [X] I confirm that this issue is not a duplicate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by devtobi** [comment]
@hupling The version number for Spring related dependencies is directly inherited using dependencyManagement mechanism via the Spring parent POM. That's why we don't version our dependencies manually. Bumping to a new Spring Boot release is probably the better idea here. However it seems like currently no new Spring boot release is available ATM. Will probably be fixed with the upcoming Spring `3.4` release. Anyways thanks for posting this issue. Will set this to blocked for now.

**Comment by hupling** [comment]
ok

**Comment by devtobi** [comment]
With the new built image of the Gateway `1.1.2` it seems like the vulnerabilities for the Java based code are gone now. (see https://artifacthub.io/packages/helm/it-at-m/refarch-gateway?modal=security-report). Only vulnerabilities in the base RedHat image, but this is out of the scope of this issue. Closing issue.
